---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: postgresql-secret
  namespace: mission-control
spec:
  encryptedData:
    password: AgB8bd2dCQ5xHD4b2tUQzBGEPBFw7ZLGrMhi7Td/Az3ybKYKD65USB3ulrEmnfdb5C6FR9gts/GTeeqSP5Lj6vSG7nXWzsd2RPTj5dhqRYIxn0zGfuAoR8gMui+qHAZYb/cQAyuhGLblQkrI+cVwhqUbJ2Bz2+qrN5aDr4ve6bCAgx5qNKa4OwQptewVGtogylrBNVzW+5cMAZ+6qzIJhjNKjy6NaefDaxgm1yDgl9OIOuvbEq8xL00D8FxHeIaRE5tek5Wyn+SHdbcAFI26C5OImHqJ4kjFjQ3uiY4ZgzmnskoACzV2h9Ub849rSaD3NaLV9qmpkEYjbhCR/DEQpy1J+NVsgm93v7Ont79aGRoF1ORUzvPhn6jbKFqGhY2ovyd2mbhTzED63DPytLSn3P0Jc1ikg6eDsgmkwD/Au7PuO9hPyFLWhrH1IbYHNL1bbzYx2KO2V5Mk8PFWnizGUe+nJHXrQyCYKhW/SJo72EFqeQcZQ1GelBWc1L9EjhLyKSQlBvSmh5Zk8x06acvnR1oM59nhXBBJtQU8Q86EzK4vbulh60r9/4fuCGpnpNHvqZdMMDpDeJHpTBkOXSWabro6M0IfPX02J8oqSUqQGJ+dpnsf4r8x0v4qwVJrf99Sw0paJ/KPYGS5n++FBtZyZb3hD2tIm7RyfP+emnebN+MoLCkb8QeRJyqHVh3DVwZHrBxK6RUvSzpJMYyh5WJHw7A0pUzguRHxQAziYCxup0JJD+H1gVUL7WtmYxFnVQ==
  template:
    metadata:
      name: postgresql-secret
      namespace: mission-control
