#!/bin/bash

# generate-sealed-secrets.sh
# Securely generates sealed secrets for mission-control environments
# These sealed secrets can be safely committed to Git
#
# Generates 2 combined SealedSecrets:
#   1. backend-secrets     - All backend env vars (PROXMOX_API_TOKEN, GEMINI_API_KEY, API_AUTH_TOKEN, POSTGRES_PASSWORD)
#   2. postgresql-secret   - PostgreSQL password (password key)

set -e

ENVIRONMENT="${1:-dev}"
NAMESPACE="mission-control"
OVERLAY_PATH="overlays/${ENVIRONMENT}/sealed-secrets"

echo "Generating sealed secrets for: ${ENVIRONMENT}"
echo "Namespace: ${NAMESPACE}"
echo "Output: ${OVERLAY_PATH}"
echo ""

# Colors for output
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

# Create sealed-secrets directory if it doesn't exist
mkdir -p "${OVERLAY_PATH}"

#############################################
# Collect credential values
#############################################

# 1. Generate Proxmox API Token
echo -e "${YELLOW}[1/4]${NC} Generating Proxmox API Token..."
PROXMOX_TOKEN=$(openssl rand -hex 32)
echo -e "${GREEN}OK${NC}"

# 2. Gemini API Key (user provides or placeholder)
echo -e "${YELLOW}[2/4]${NC} Gemini API Key..."
read -p "Enter your Gemini API Key (or press Enter to use placeholder): " GEMINI_KEY
if [ -z "$GEMINI_KEY" ]; then
  GEMINI_KEY="REPLACE_WITH_YOUR_GEMINI_API_KEY"
fi
echo -e "${GREEN}OK${NC}"

# 3. Generate Backend Auth Token
echo -e "${YELLOW}[3/4]${NC} Generating Backend Auth Token..."
API_TOKEN=$(openssl rand -hex 32)
echo -e "${GREEN}OK${NC}"

# 4. Generate PostgreSQL Password
echo -e "${YELLOW}[4/4]${NC} Generating PostgreSQL Password..."
POSTGRES_PASS=$(openssl rand -base64 32)
echo -e "${GREEN}OK${NC}"

echo ""

#############################################
# Create SealedSecret 1: backend-secrets
# (matches deployment envFrom: secretRef)
#############################################

echo "Sealing backend-secrets (combined)..."
kubectl create secret generic backend-secrets \
  --namespace="${NAMESPACE}" \
  --from-literal=PROXMOX_API_TOKEN="${PROXMOX_TOKEN}" \
  --from-literal=GEMINI_API_KEY="${GEMINI_KEY}" \
  --from-literal=API_AUTH_TOKEN="${API_TOKEN}" \
  --from-literal=POSTGRES_PASSWORD="${POSTGRES_PASS}" \
  --dry-run=client \
  -o yaml | kubeseal -o yaml > "${OVERLAY_PATH}/backend-secrets.yaml"
echo -e "${GREEN}OK${NC} backend-secrets sealed"

#############################################
# Create SealedSecret 2: postgresql-secret
# (matches statefulset/deployment secretKeyRef)
#############################################

echo "Sealing postgresql-secret..."
kubectl create secret generic postgresql-secret \
  --namespace="${NAMESPACE}" \
  --from-literal=password="${POSTGRES_PASS}" \
  --dry-run=client \
  -o yaml | kubeseal -o yaml > "${OVERLAY_PATH}/postgresql-secret.yaml"
echo -e "${GREEN}OK${NC} postgresql-secret sealed"

#############################################
# Generate kustomization.yaml
#############################################

cat > "${OVERLAY_PATH}/kustomization.yaml" <<EOF
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Sealed secrets for mission-control ${ENVIRONMENT} environment
# Generated by: ./scripts/generate-sealed-secrets.sh ${ENVIRONMENT}
# These are encrypted and safe to commit to Git

resources:
  - backend-secrets.yaml
  - postgresql-secret.yaml
EOF
echo -e "${GREEN}OK${NC} kustomization.yaml generated"

#############################################
# Summary
#############################################

echo ""
echo -e "${GREEN}All sealed secrets generated successfully!${NC}"
echo ""
echo "Generated Files:"
echo "  - ${OVERLAY_PATH}/backend-secrets.yaml"
echo "  - ${OVERLAY_PATH}/postgresql-secret.yaml"
echo "  - ${OVERLAY_PATH}/kustomization.yaml"
echo ""
echo "IMPORTANT - Save these credentials securely:"
echo "-------------------------------------------------------"
echo "PROXMOX_API_TOKEN: ${PROXMOX_TOKEN}"
echo "GEMINI_API_KEY: ${GEMINI_KEY}"
echo "API_AUTH_TOKEN: ${API_TOKEN}"
echo "POSTGRES_PASSWORD: ${POSTGRES_PASS}"
echo "-------------------------------------------------------"
echo ""
echo "These sealed secrets are encrypted and safe to commit to Git"
echo ""
echo "Next steps:"
echo "  1. Commit and push to trigger ArgoCD deployment"
echo "  2. Store the plain credentials above in your password manager"
